apiVersion: v1
kind: ServiceAccount
metadata:
  name: agile-pm
  namespace: agile-pm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agile-pm
  namespace: agile-pm
rules: []  # Minimal permissions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agile-pm
  namespace: agile-pm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agile-pm
subjects:
  - kind: ServiceAccount
    name: agile-pm
    namespace: agile-pm
